const options = {
  client: 'pg',
  connection: {
    host: '127.0.0.1',
    user: 'me',
    password: 'test123',
    database: 'schedule',
  },
};
const ramSchedule = [{
  id: 1,
  vs: ' vs ',
  city: 'Arizona',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 1,
  date: '28-Oct-2018',
  opponent: 'Cardinals',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/ari.png&h=40&w=40',
  result: ' 34-0',
  winloss: '1-0',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/ari/arizona-cardinals',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Cooks',
  pass: 270,
  rush: 141,
  rec: 111,
}, {
  id: 2,
  vs: ' @ ',
  city: 'Atlanta',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 2,
  date: '08-Dec-2018',
  opponent: 'Falcons',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/atl.png&h=40&w=40',
  result: '  23-20',
  winloss: '2-0',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/atl/atlanta-falcons',
  playerpass: 'Goff',
  playerrush: 'Brown',
  playerrec: 'Woods',
  pass: 325,
  rush: 128,
  rec: 119,
}, {
  id: 3,
  vs: ' vs ',
  city: 'Denver',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 3,
  date: '16-Sep-2018',
  opponent: 'Broncos',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/den.png&h=40&w=40',
  result: ' 30-23',
  winloss: '2-1',
  wl: ' L',
  link: 'http://www.espn.com/nfl/team/_/name/den/denver-broncos',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Woods',
  pass: 219,
  rush: 207,
  rec: 98,
}, {
  id: 4,
  vs: ' vs ',
  city: 'Green Bay',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 4,
  date: '11-Sep-2018',
  opponent: 'Packers',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/gb.png&h=40&w=40',
  result: ' W 14-0',
  winloss: '3-1',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/gb/green-bay-packers',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Woods',
  pass: 287,
  rush: 62,
  rec: 172,
}, {
  id: 5,
  vs: ' @ ',
  city: 'Kansas City',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 5,
  date: '10-Nov-2018',
  opponent: 'Chiefs',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/kc.png&h=40&w=40',
  result: ' 39-10',
  winloss: '4-1',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/kc/kansas-city-chiefs',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Kupp',
  pass: 366,
  rush: 64,
  rec: 140,
}, {
  id: 6,
  vs: ' vs ',
  city: 'San Francisco',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 6,
  date: '09-Nov-2018',
  opponent: '49ers',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/sf.png&h=40&w=40',
  result: ' 35-23',
  winloss: '5-1',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/sf/san-francisco-49ers',
  playerpass: 'Goff',
  playerrush: 'Brown',
  playerrec: 'Woods',
  pass: 425,
  rush: 129,
  rec: 201,
}, {
  id: 7,
  vs: ' @ ',
  city: 'Washington',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 7,
  date: '18-Nov-2018',
  opponent: 'Redskins',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/wsh.png&h=40&w=40',
  result: ' 30-23',
  winloss: '5-2',
  wl: ' L',
  link: 'http://www.espn.com/nfl/team/_/name/wsh/washington-redskins',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Cooks',
  pass: 360,
  rush: 66,
  rec: 125,
}, {
  id: 8,
  vs: ' vs ',
  city: 'Jacksonville',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 8,
  date: '12-Dec-2018',
  opponent: 'Jaguars',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/jax.png&h=40&w=40',
  result: ' 38-31',
  winloss: '6-2',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/jax/jacksonville-jaguars',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Woods',
  pass: 192,
  rush: 68,
  rec: 95,
}, {
  id: 9,
  vs: ' @ ',
  city: 'Buffalo',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 9,
  date: '13-Nov-2018',
  opponent: 'Bills',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/buf.png&h=40&w=40',
  result: ' 45-35',
  winloss: '6-3',
  wl: ' L',
  link: 'http://www.espn.com/nfl/team/_/name/buf/buffalo-bills',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Woods',
  pass: 274,
  rush: 119,
  rec: 224,
}, {
  id: 10,
  vs: '',
  city: '',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 10,
  date: 'BYE WEEK',
  opponent: 'BYE WEEK',
  opponentlogo: 'https://cdn.shocho.co/sc-site/brandPages/Grills/Jeeva_logo_small_-_transparent_PNG_file_400x400-1.png',
  result: '',
  winloss: '',
  wl: '',
  link: '',
  playerpass: '',
  playerrush: '',
  playerrec: '',
  pass: 0,
  rush: 0,
  rec: 0,
}, {
  id: 11,
  vs: ' @ ',
  city: 'Indianapolis',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 11,
  date: '16-Nov-2018',
  opponent: 'Colts',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/ind.png&h=40&w=40',
  result: ' 54-51',
  winloss: '7-3',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/ind/indianapolis-colts',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Kupp',
  pass: 184,
  rush: 172,
  rec: 110,
}, {
  id: 12,
  vs: ' vs ',
  city: 'Baltimore',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 12,
  date: '11-Sep-2018',
  opponent: 'Ravens',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/bal.png&h=40&w=40',
  result: ' 30-16',
  winloss: '8-3',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/bal/baltimore-ravens',
  playerpass: 'Goff',
  playerrush: 'Brown',
  playerrec: 'Cooks',
  pass: 230,
  rush: 241,
  rec: 189,
}, {
  id: 13,
  vs: ' vs ',
  city: 'Miami',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 13,
  date: '24-Nov-2018',
  opponent: 'Dolphins',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/mia.png&h=40&w=40',
  result: ' 29-27',
  winloss: '9-3',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/mia/miami-dolphins',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Cooks',
  pass: 367,
  rush: 63,
  rec: 170,
}, {
  id: 14,
  vs: ' @ ',
  city: 'Cleveland',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 14,
  date: '30-Nov-2018',
  opponent: 'Browns',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/cle.png&h=40&w=40',
  result: ' 33-13',
  winloss: '10-3',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/cle/cleveland-browns',
  playerpass: 'Goff',
  playerrush: 'Brown',
  playerrec: 'Woods',
  pass: 218,
  rush: 216,
  rec: 144,
}, {
  id: 15,
  vs: ' vs ',
  city: 'Cincinnati',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 15,
  date: '15-Dec-2018',
  opponent: 'Bengals',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/cin.png&h=40&w=40',
  result: ' 35-23',
  winloss: '11-3',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/cin/cincinnati-bengals',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Gurley II',
  pass: 242,
  rush: 269,
  rec: 210,
}, {
  id: 16,
  vs: ' vs ',
  city: 'Los Angeles',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 16,
  date: '08-Oct-2018',
  opponent: 'Chargers',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/lac.png&h=40&w=40',
  result: ' 23-20',
  winloss: '12-3',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/lac/los-angeles-chargers',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Cooks',
  pass: 154,
  rush: 150,
  rec: 228,
}, {
  id: 17,
  vs: ' vs ',
  city: 'Detroit',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 17,
  date: '26-Oct-2018',
  opponent: 'Lions',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/det.png&h=40&w=40',
  result: ' 31-3',
  winloss: '13-3',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/det/detroit-lions',
  playerpass: 'Goff',
  playerrush: 'Brown',
  playerrec: 'Woods',
  pass: 312,
  rush: 130,
  rec: 246,
}, {
  id: 18,
  vs: ' vs ',
  city: 'New England',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 18,
  date: '25-Jan-2019',
  opponent: 'Patriots',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/ne.png&h=40&w=40',
  result: ' W 33-3',
  winloss: '14-3',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/ne/new-england-patriots',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Woods',
  pass: 312,
  rush: 130,
  rec: 246,
}, {
  id: 19,
  vs: ' vs ',
  city: 'New York',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 19,
  date: '31-Jan-2019',
  opponent: 'Jets',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/nyj.png&h=40&w=40',
  result: ' 43-3',
  winloss: '15-3',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/nyj/new-york-jets',
  playerpass: 'Goff',
  playerrush: 'Gurley II',
  playerrec: 'Cooks',
  pass: 312,
  rush: 130,
  rec: 246,
}, {
  id: 20,
  vs: ' vs ',
  city: 'Pittsburgh',
  team: 'Los Angeles Rams',
  teamlogo: 'http://icons.iconarchive.com/icons/astahrr/nfl/48/Rams-icon.png',
  week: 20,
  date: '7-Feb-2019',
  opponent: 'Steelers',
  opponentlogo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/scoreboard/pit.png&h=40&w=40',
  result: ' 13-3',
  winloss: '16-3',
  wl: ' W',
  link: 'http://www.espn.com/nfl/team/_/name/pit/pittsburgh-steelers',
  playerpass: 'Goff',
  playerrush: 'Brown',
  playerrec: 'Kupp',
  pass: 312,
  rush: 130,
  rec: 246,
},
];

const knex = require('knex')(options);

knex('stats').insert(ramSchedule).then(() => console.log('data inserted'))
  .catch((err) => { console.log(err); throw err; })
  .finally(() => {
    knex.destroy();
  });